whattocook/recipes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^showrecipe/(?P<recipe_id>[0-9]+)/$', views.showrecipe, name='showrecipe'),
    url(r'^addrecipe/$', views.addrecipe, name='addrecipe'),
]

whattocook/whattocook/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^recipes/', include('recipes.urls', namespace='recipes')),
    url(r'^admin/', admin.site.urls),
]

whattocook/recipes/models.py
from django.db import models


# Create your models here.

class IngredientNameManager(models.Manager):
    def create_if_not_exists(self, self_id, name):
        if self.filter(pk=self_id).exists():
            return
        self.create(pk=self_id, name=name).save()


class IngredientName(models.Model):
    name = models.CharField(max_length=500)
    objects = IngredientNameManager()

    def __str__(self):
        return self.name


class IngredientAmount(models.Model):
    ingredient_id = models.IntegerField()
    amount = models.IntegerField()
    units = models.CharField(max_length=100)

    def __str__(self):
        return u'id=' + str(self.ingredient_id) + u', amount=' + self.amount + self.units


class Recipe(models.Model):
    summary = models.CharField(max_length=500)
    plates = models.IntegerField(default=1)
    time = models.CharField(max_length=50, blank=True)
    title = models.CharField(max_length=500, default='')
    ingredients = models.ManyToManyField(IngredientAmount)
    link = models.CharField(max_length=500)
    add_time = models.DateTimeField()

    def __str__(self):
        return self.title

whattocook/recipes/views.py
# -*- coding: utf-8 -*-

import re
import requests

from django.http import HttpResponse, Http404, HttpResponseBadRequest, HttpResponseRedirect
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.db import transaction
from django.core.urlresolvers import reverse
from django.template import loader
from django.utils import timezone

from .models import *


def index(request):
    template = loader.get_template('titlepage.html')
    context = {'last_recipes': Recipe.objects.order_by('add_time').all()[:5]}
    return HttpResponse(template.render(context, request))


def parse_amount(amount_units):
    words = amount_units.split()
    if not words:
        return -1, ''
    if len(words) == 1:
        return -1, words[0]
    try:
        words[0] = int(words[0])
    except ValueError:
        return -1, ' '.join(words)
    return words[0], ' '.join(words[1:])


@require_POST
def addrecipe_post(request):
    recipe_id = request.POST['id']
    try:
        recipe_id = int(recipe_id)
    except ValueError:
        return HttpResponseBadRequest()

    if Recipe.objects.filter(pk=recipe_id).exists():
        return HttpResponseRedirect(reverse('recipes:showrecipe', args=(recipe_id,)))

    ingredientexpr = re.compile(
        r"<span itemprop=\"ingredient\"[^>]*><[^>]*www\.povarenok\.ru/recipes/ingredient/(\d+)[^>]*>[^>]*>([^<]+)[^>]*>[^>]*>[^>]*>([^<]+)<")
    remscriptsexpr = re.compile(r"<(S|s)cript[^>]*></(S|s)cript>")
    timeexpr = re.compile(r"<time datetime=\"([^\"]+)\"[^>]*>([^<]+)<")
    platesexpr = re.compile(u"<strong>Количество порций:</strong>([^<]+)<")
    summaryexpr = re.compile(r"<span itemprop=\"summary\">([^<]+)<")
    titleexpr = re.compile(r"<h1><[^>]*>([^<]+)<")

    req = requests.get(r'http://www.povarenok.ru/recipes/show/' + str(recipe_id) + r'/')
    if req.status_code != requests.codes.ok:
        return HttpResponseBadRequest()
    data = req.text
    data = remscriptsexpr.sub("", data)

    title = titleexpr.search(data).group(1).strip()

    summary = summaryexpr.search(data).group(1).strip()

    timeneeded = timeexpr.search(data)
    if timeneeded is None:
        #timeneeded = ("N/A", "?")
        time = ""
    else:
        timeneeded = (timeneeded.group(1), timeneeded.group(2).strip())
        time = timeneeded[1]

    plates = platesexpr.search(data)
    if plates is None:
        plates = 1
    else:
        plates = plates.group(1).strip()

    with transaction.atomic():
        recipe = Recipe(id=recipe_id, title=title, summary=summary, plates=plates, time=time, add_time=timezone.now())
        recipe.save()

        ingredients = ingredientexpr.findall(data)
        for ing in ingredients:
            ing_amount, ing_units = parse_amount(ing[2])
            print('amount = {}, units = {}'.format(ing_amount, ing_units))
            ingredient_amount = IngredientAmount(amount=ing_amount, units=ing_units, ingredient_id=ing[0])
            ingredient_amount.save()
            recipe.ingredients.add(ingredient_amount)
            IngredientName.objects.create_if_not_exists(ing[0], ing[1])
        recipe.save()
    return HttpResponseRedirect(reverse('recipes:showrecipe', args=(recipe_id,)))


def addrecipe_get(request):
    template = loader.get_template('addrecipe.html')
    return HttpResponse(template.render({}, request))


def addrecipe(request):
    if request.method == 'POST':
        return addrecipe_post(request)
    else:
        return addrecipe_get(request)


def showrecipe(request, recipe_id):
    template = loader.get_template('showrecipe.html')
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    context = {
        "id": recipe_id,
        "recipe": recipe,
        "ingredients": []
    }
    for ing_amount in recipe.ingredients.all():
        ing = IngredientName.objects.get(pk=ing_amount.ingredient_id)
        context["ingredients"].append({"name": ing.name, "amount": str(ing_amount.amount) + " " + ing_amount.units})
        if ing_amount.amount == -1:
            context["ingredients"][-1]["amount"] = ing_amount.units
    return HttpResponse(template.render(context, request))

whattocook/recipes/templates/addrecipe.html
<form action="{% url 'recipes:addrecipe' %}" method="POST">
{% csrf_token %}
<input type="text" name="id" value=""></input>
<input type="submit" value="Add!" />
</form>

whattocook/recipes/templates/base.html
<html>
<head>
    <title>{% block title %}his-own-chef.ru - Сам себе повар{% endblock %}</title>
    <style type="text/css">
        #header {
            box-sizing: border-box;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: baseline;
            margin-left: 5%;
            width: 90%;
            margin-bottom: 40px;
        }

        #header a {
            text-decoration: none;
            font-weight: bold;
        }

        #header a:hover {
            text-decoration: underline;
        }

        #header button {
            background: cornflowerbluee;
            border-color: cornflowerblue;
            border-radius: 3px;
        }
        
        #content {
            width: 60%;
            margin: auto;
        }


        #last-added-recipes {
            padding: 30px;
        }
        
        div.recipe-short {
            margin-bottom: 20px;
        }
        
        div.recipe-short h2 {
            margin-bottom: 3px;
        }
        
        div.recipe-short p {
            margin-top: 3px;
        }
        
        div.ingredient {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: baseline;
            padding-bottom: 3px;
            border-bottom: 2px #98b0c7 solid;
            margin-bottom: 5px;
        }

        body {
            background-color: lightsteelblue;
        }
    </style>
</head>
<body>
{% block body %}
<div id="header">
<button><a href="/recipes/addrecipe">Добавить свой рецепт</a></button>
<button><a href="/recipes">Предложить рецепт</a></button>
<button><a href="/recipes">Найти рецепт</a></button>
<button><a href="/recipes">Войти/Зарегистрироваться</a></button>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
{% endblock %}
</body>
</html>

whattocook/recipes/templates/showrecipe.html
{% extends "base.html" %}

{% block title %}{{recipe.title}}{% endblock %}

{% block content %}
<h1>{{recipe.title}}</h1>
<h2>Описание:</h2>
<p>{{recipe.summary}}</p>
<p>{{recipe.time}}</p>
<p>Количество порций: {{recipe.plates}}</p>
<h2>Вам необходимо:</h2>
{% for ing in ingredients %}
	<div class="ingredient"><span>{{ing.name}}:</span><span>{{ing.amount}}</span></div>
{% endfor %}
{% endblock %}

whattocook/recipes/templates/titlepage.html
<html>
<head>
    <title>his-own-chef.ru - Сам себе повар</title>
    <style type="text/css">
        #header {
            box-sizing: border-box;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: baseline;
            margin-left: 5%;
            width: 90%;
            margin-bottom: 40px;
        }
        #header a {
        text-decoration: none;
        font-weight: bold;
        }
        #header a:hover {
        text-decoration: underline;
        }

        #last-added-recipes {
        padding: 30px;
        }

        div.recipe-short {
        margin-bottom: 10px;
        padding: 3px;
        border-radius: 3px;
        }
        div.recipe-short h2 {
        margin-bottom: 3px;
        }
        div.recipe-short p {
        margin-top: 3px;
        }
        div.recipe-short:hover {
        cursor: pointer;
        background-color: #A0B4CE;
        }

        div.button{
        background: cornflowerbluee;
        border-color: cornflowerblue;
        border-radius: 3px;
        }

        body {background-color: lightsteelblue;}
    </style>
</head>
<body>
<div id="header">
<button class="button"><a href="/recipes">Добавить свой рецепт</a></button>
<button class="button"><a href="/recipes">Предложить рецепт</a></button>
<button class="button"><a href="/recipes">Найти рецепт</a></button>
<button class="button"><a href="/recipes">Войти/Зарегистрироваться</a></button>
</div>
<table>
    <tr>
        <td id="last-added-recipes">
            <h1>Последние добавленные</h1>
            {% for recipe in last_recipes %}
            <div class="recipe-short" onclick="window.location.href='/recipes/showrecipe/{{recipe.pk}}';">
                <h2>{{ recipe.title | safe }}</h2>
                <p> Время приготовления: {{ recipe.time }}</p>
            </div>
            {% endfor %}
        </td>
        <td id="find-recipe">
        бла-бла-бла
        тут будет игра
        </td>
    </tr>
</table>
</body>
</html>